<?
$PERM["sellersAccount"]["2"]="D";
$PERM["sellersAccount"]["6"]="D";
$PERM["sellersAccount"]["7"]="X";
$PERM["sellersAccount"]["*"]="D";
$PERM["buyersAccount"]["2"]="D";
$PERM["buyersAccount"]["6"]="X";
$PERM["buyersAccount"]["7"]="D";
$PERM["buyersAccount"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>